/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	podwatchers_nahid_try_com_v1alpha1 "kubernetes-practice/k8s-custom-resource/pkg/apis/podwatchers.nahid.try.com/v1alpha1"
	versioned "kubernetes-practice/k8s-custom-resource/pkg/client/clientset/versioned"
	internalinterfaces "kubernetes-practice/k8s-custom-resource/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubernetes-practice/k8s-custom-resource/pkg/client/listers/podwatchers.nahid.try.com/v1alpha1"
	time "time"
)

// PodWatcherInformer provides access to a shared informer and lister for
// PodWatchers.
type PodWatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodWatcherLister
}

type podWatcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodWatcherInformer constructs a new informer for PodWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodWatcherInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodWatcherInformer constructs a new informer for PodWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodwatchersV1alpha1().PodWatchers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodwatchersV1alpha1().PodWatchers(namespace).Watch(options)
			},
		},
		&podwatchers_nahid_try_com_v1alpha1.PodWatcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *podWatcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodWatcherInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podWatcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podwatchers_nahid_try_com_v1alpha1.PodWatcher{}, f.defaultInformer)
}

func (f *podWatcherInformer) Lister() v1alpha1.PodWatcherLister {
	return v1alpha1.NewPodWatcherLister(f.Informer().GetIndexer())
}
